# Generated by Django 6.0.4 on 2026-06-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variatios',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
