# Generated by Django 6.0.4 on 2026-06-08 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_variatios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='variatios',
            new_name='variations',
        ),
    ]
